[phases.setup]
nixPkgs = ["python311", "unzip", "wget"]

[phases.build]
cmds = [
    # Download the Lune executable
    "wget https://github.com/lune-org/lune/releases/download/v0.8.8/lune-0.8.8-linux-x86_64.zip",
    # Unzip it
    "unzip -o lune-0.8.8-linux-x86_64.zip",
    # Make it executable
    "chmod +x lune",
    # Install Python requirements
    "pip install -r requirements.txt",
    "playwright install",
    "playwright install-deps"
]

[start]
cmd = "python bot.py"
